// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mQC
List mQC(NumericMatrix bc_counts, IntegerMatrix codebook, int max_correctable_Hamming_distance, double ctol, int max_evals, int n_resamples);
RcppExport SEXP _FISHmQC_mQC(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP max_correctable_Hamming_distanceSEXP, SEXP ctolSEXP, SEXP max_evalsSEXP, SEXP n_resamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type max_correctable_Hamming_distance(max_correctable_Hamming_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type ctol(ctolSEXP);
    Rcpp::traits::input_parameter< int >::type max_evals(max_evalsSEXP);
    Rcpp::traits::input_parameter< int >::type n_resamples(n_resamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC(bc_counts, codebook, max_correctable_Hamming_distance, ctol, max_evals, n_resamples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FISHmQC_mQC", (DL_FUNC) &_FISHmQC_mQC, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_FISHmQC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
