# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mQC <- function(bc_counts, codebook, max_correctable_Hamming_distance, ctol = 1e-7, max_evals = 500L, n_resamples = 100L) {
    .Call(`_FISHmQC_mQC`, bc_counts, codebook, max_correctable_Hamming_distance, ctol, max_evals, n_resamples)
}

