# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mQC <- function(bc_counts, codebook, max_correctable_Hamming_distance) {
    .Call(`_FISHmQC_mQC`, bc_counts, codebook, max_correctable_Hamming_distance)
}

