# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_flip_rates_initial_R <- function(bc_countsR, codebook, max_correctable_Hamming_distance) {
    .Call(`_FISHmQC_estimate_flip_rates_initial_R`, bc_countsR, codebook, max_correctable_Hamming_distance)
}

